alerting:
  alertmanagers:
  - scheme: http
  - static_configs:
    - targets:
      - alertmanager:9093
global:
  evaluation_interval: 5s
  external_labels:
    monitor: crane-monitor
  scrape_interval: 5s
rule_files:
- rules.yml
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
- job_name: prueba_demo_crane-1
  scrape_interval: 5s
  static_configs:
  - targets:
    - 172.24.0.4:8080
