groups:
  - name: Services
    rules:
      - alert: service_down
        expr: up == 0
        for: 30s
        labels:
          severity: page
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 30 seconds."

      - alert: high_load
        expr: node_load1 > 0.8
        for: 30s
        labels:
          severity: page
        annotations:
          summary: "Instance {{ $labels.instance }} under high load"
          description: "{{ $labels.instance }} of job {{ $labels.job }} is under high load."

      - alert: site_down
        expr: probe_success < 1
        for: 30s
        labels:
          severity: page
        annotations:
          summary: "Site Down: {{$labels.instance}}"
          description: "Site Down: {{$labels.instance}} for more than 30 seconds"

      - alert: site_slow
        expr: probe_duration_seconds > 1
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "Site Slow: {{$labels.instance}}"
          description: "Site Slow: {{$labels.instance}} for more than 30 seconds"

      - alert: high_request_count
        expr: traefik_entrypoint_requests_total > 100
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High request count for Traefik"
          description: "The request count for Traefik entrypoint is consistently high."
