volumes:
  prometheus_data: {}
  alertmanager_data: {}

networks:
  prometheus-net:
    external: true
services:
  prometheus:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
      - ./prometheus/rules.yml:/etc/prometheus/rules.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9090:9090
    restart: always
    networks:
      - default
      - prometheus-net
    links:
      - alertmanager:alertmanager
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: always
    ports:
      - 9093:9093
    volumes:
      - "./alertmanager/:/config"
      - "alertmanager_data:/data"
    command: --config.file=/config/alertmanager.yml
    networks:
      - default
      - prometheus-net
